# Generated by Django 5.2.3 on 2025-06-24 16:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sos_type', models.IntegerField(choices=[(0, 'Emergency'), (1, 'Alert')], default=0)),
                ('status_flag', models.IntegerField(choices=[(0, 'Unresolved'), (1, 'Resolved')], default=0)),
                ('initial_latitude', models.FloatField()),
                ('initial_longitude', models.FloatField()),
                ('unit_number_dispatched', models.CharField(blank=True, max_length=50, null=True)),
                ('acknowledged_flag', models.IntegerField(choices=[(0, 'Not Acknowledged'), (1, 'Acknowledged')], default=0)),
                ('room_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SOS',
                'verbose_name_plural': 'SOS Requests',
            },
        ),
        migrations.CreateModel(
            name='OfficerAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('officer_name', models.CharField(max_length=255)),
                ('unit_number', models.CharField(max_length=50)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('sos_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='officer_assignments', to='api.sos')),
            ],
        ),
        migrations.CreateModel(
            name='LocationUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('sos_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_updates', to='api.sos')),
            ],
        ),
    ]
