name: naarikavach
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - asgiref=3.8.1
  - bidict=0.23.1
  - ca-certificates=2025.6.15
  - cffi=1.17.1
  - cryptography=45.0.4
  - djangorestframework=3.16.0
  - dnspython=2.7.0
  - greenlet=3.2.3
  - h11=0.16.0
  - libffi
  - openssl
  - pip
  - pycparser=2.22
  - pyopenssl=25.1.0
  - python-engineio=4.12.2
  - python-socketio=5.13.0
  - setuptools=80.9.0
  - simple-websocket=1.1.0
  - sniffio=1.3.1
  - sqlparse=0.5.3
  - typing-extensions=4.14.0
  - wheel=0.45.1
  - wsproto=1.2.0
  - pip:
      - async-timeout==5.0.1
      - attrs==25.3.0
      - autobahn==24.4.2
      - automat==25.4.16
      - certifi==2025.6.15
      - channels==4.2.2
      - channels-redis==4.2.1
      - charset-normalizer==3.4.2
      - click==8.2.1
      - constantly==23.10.4
      - daphne==4.2.0
      - defusedxml==0.7.1
      - django==5.2.3
      - djangorestframework-simplejwt==5.5.0
      - djoser==2.3.1
      - hyperlink==21.0.0
      - idna==3.10
      - incremental==24.7.2
      - msgpack==1.1.1
      - oauthlib==3.3.1
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pyjwt==2.9.0
      - python3-openid==3.2.0
      - redis==6.2.0
      - requests==2.32.4
      - requests-oauthlib==2.0.0
      - service-identity==24.2.0
      - social-auth-app-django==5.4.3
      - social-auth-core==4.6.1
      - tomli==2.2.1
      - twisted==25.5.0
      - txaio==23.1.1
      - urllib3==2.5.0
      - uvicorn==0.34.3
      - zope-interface==7.2
      - aiohttp
